-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    id integer NOT NULL DEFAULT nextval('admin_id_seq'::regclass),
    surname character varying(45) COLLATE pg_catalog."default" NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    middlename character varying(45) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admin_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.child_count
(
    count integer
);

CREATE TABLE IF NOT EXISTS public.children
(
    id integer NOT NULL DEFAULT nextval('children_id_seq'::regclass),
    id_parent integer NOT NULL,
    id_group integer NOT NULL,
    surname character varying(45) COLLATE pg_catalog."default" NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    middlename character varying(45) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    date_birth date NOT NULL,
    adress character varying(80) COLLATE pg_catalog."default" NOT NULL,
    date_reg date NOT NULL,
    CONSTRAINT children_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.doc
(
    id integer NOT NULL DEFAULT nextval('doc_id_seq'::regclass),
    name_id integer NOT NULL,
    CONSTRAINT doc_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.groups
(
    id integer NOT NULL DEFAULT nextval('groups_id_seq'::regclass),
    group_year integer NOT NULL,
    group_number integer NOT NULL,
    count integer NOT NULL DEFAULT 25,
    CONSTRAINT groups_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.parents
(
    id integer NOT NULL DEFAULT nextval('parents_id_seq'::regclass),
    surname character varying(45) COLLATE pg_catalog."default" NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    middlename character varying(45) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    processing_inf boolean NOT NULL,
    mail character varying(80) COLLATE pg_catalog."default" NOT NULL,
    date_reg date NOT NULL DEFAULT now(),
    status_pay boolean NOT NULL,
    CONSTRAINT parents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.passport
(
    id integer NOT NULL DEFAULT nextval('passport_id_seq'::regclass),
    series character varying(4) COLLATE pg_catalog."default" NOT NULL,
    "number" character varying(6) COLLATE pg_catalog."default" NOT NULL,
    issued character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT passport_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket
(
    id integer NOT NULL DEFAULT nextval('ticket_id_seq'::regclass),
    there boolean NOT NULL DEFAULT false,
    back boolean NOT NULL DEFAULT false,
    CONSTRAINT ticket_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vaccination
(
    id integer NOT NULL DEFAULT nextval('vaccination_id_seq'::regclass),
    date_bcj date NOT NULL,
    date_akds date NOT NULL,
    date_polio date NOT NULL,
    CONSTRAINT vaccination_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.children
    ADD CONSTRAINT children_id_group_fkey FOREIGN KEY (id_group)
    REFERENCES public.groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.children
    ADD CONSTRAINT children_id_parent_fkey FOREIGN KEY (id_parent)
    REFERENCES public.parents (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.doc
    ADD CONSTRAINT doc_id_fkey FOREIGN KEY (id)
    REFERENCES public.children (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS doc_pkey
    ON public.doc(id);


ALTER TABLE IF EXISTS public.passport
    ADD CONSTRAINT passport_id_fkey FOREIGN KEY (id)
    REFERENCES public.children (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS passport_pkey
    ON public.passport(id);


ALTER TABLE IF EXISTS public.ticket
    ADD CONSTRAINT ticket_id_fkey FOREIGN KEY (id)
    REFERENCES public.children (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS ticket_pkey
    ON public.ticket(id);


ALTER TABLE IF EXISTS public.vaccination
    ADD CONSTRAINT vaccination_id_fkey FOREIGN KEY (id)
    REFERENCES public.children (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS vaccination_pkey
    ON public.vaccination(id);

END;